[platformio]
default_envs = t_display_p4_tft

[env]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-p4
framework = espidf
monitor_speed = 115200
board_build.sdkconfig = sdkconfig.defaults
extra_scripts = pre:scripts/vendor_components.py
build_flags =
  -std=gnu++20
  -Wall
  -Wextra
  -Werror=return-type

[env:t_display_p4_tft]
build_flags =
  ${env.build_flags}
  -DCONFIG_SCREEN_TYPE_HI8561=1

[env:t_display_p4_amoled]
build_flags =
  ${env.build_flags}
  -DCONFIG_SCREEN_TYPE_RM69A10=1
